%% Optimizacio Solver
clc, clear all, close all;

%% Parametros del optimizador
options = optimset('Display','iter',...
                'TolFun', 1e-8,...
                'MaxIter', 10000,...
                'Algorithm', 'active-set',...
                'FinDiffType', 'forward',...
                'RelLineSrchBnd', [],...
                'RelLineSrchBndDuration', 1,...
                'TolConSQP', 1e-6); 
            
% Limits acontrol actions
x_low = [0.1; 0.1; 0.1; 0.1];
x_up = [50; 50; 50; 50];
x0=zeros(1,4)+0.1;           
f_obj1 = @(x)  Tele_no_delay(x);
x = fmincon(f_obj1,x0,[],[],[],[],x_low,x_up,[],options);
chi = x